filter:
  excluded_paths:
    - Tests/*

build:
  environment:
    php: '7.4'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      tests:
        override:
          - command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
            coverage:
              file: 'coverage-file'
              format: 'clover'
